language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "sulekhadahiya-github"
    token:
      secure: UfPcIoGDGOlUSVFic6mD2x8KO7u67Cl0QiryJlmDltXkxbkwAW+pmobh6vavqltfjfEugnopeeNUmiC4xwov1xu6rcOjCYQL1DOUFgDYzjt8FSdAVievJZJphBohabmIQCpcghZtECIkgwqpcCH8JHLKPxBf08J0mMUtzQNNEAzFwVvjZdimshADCLCi8fjgtdgZ1rBF61AAD0wxPkLLGdqgVuUKVyCf2ZA8yiFy7tDORFWAJI9WigL7g0sXlvrJ0GgZXhFR8bBreLx8q5FyDndZi35JkJhNDykQbJ7VFd+Ry8j2VNOrB84IiXg1nfT6TyzFwC4YOMPtDdDrzzVxcCH5bNQ706sy1gDRnS5AQOWPZ0qlWcxbpmsZI2UdTT8tMmBQQU3NnkY9UprnAPxBxzG3abQdN22DSz0ZExhaI6HNbgZYo+YUsHdO89995eIiftk0Rqwoywvuwfr6pw80SpJBerOYadmlqegBrE7Cv+YRI40NKh5OsLlSjjbjL3gzUxVXf3r57d/70dPeI8fcOujwOIUTNrUVuHR61c8g0sTt0Ae7+o5lkpMmEDjEuSbE5+sSMOIVj/xoO7Nt4keM+uxNWVSwv/PLzU/MdotHswskUohGRBWbRKvEoDRRsvC1m9i0AXr5PTkG+umntwBjfYFnsV9txGAk9KYRLooSDMo= # encrypted value of your token

script:
  - "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

notifications:
  slack:
    secure: i4r1hgPgXfv4WJNheHhJyU/QVSlM1fsyJDraW8e+0/58I94cxdXlofsqcyAPi7kje34ySEAOCh5bGjBFczz/zFxf7ghhFcpwZP9DxrFqnZhHb/Io84HWYYlIcpn0JDzbRNDqXgEUtjap5PTVXF5+4o9WyBYdxjhCWqdiRczGcDkapR5QlSBOV6vVuTBeOKLNqb6WK5kNQ8VsL9GU5ECkhgYlAhSY6QaT2f4m8IlHMgng6O2qI4XLEBDb+cJeEwaWu3UjhsfwLusQAyVWvnJQI0EI7bHw35LEnmwDK0F1CF4t6SBvPvNdzB2KNN9tKKWn28ob4hvoYRTNhk98Qh8yeytlEd83dRW8jSDxDF1KDq5e0/bt68AN8fIDbUp6+grRztfZ79a7TxSGnbRBejb1mh84nUp1jk3QrsqinsLjsOQD+O8KQsgBYBpYJm2/bv8ZRvF/Wh1k2ctbOhw4Z27hYknqRt7bGEsYkFs08H4AaoOaJHrtFSPsu4Ptog+WNIH98wHts4gHCypl3Sr/EhqLYR9z2ASP6bu6BMZ5CQ1NWIql2ydvmQioHKUcUpJWHYiPksQaOuUq8EirbFTzP5npBELpxPWS51KLr/ozXck6xhcBtFON7/FaaMb7tB92Bt50f23s44XjpNZZJhIfBltRdffoXkj8e9PJrtqbVrqXtiI=

