language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "sulekhadahiya-github"
    token:
      secure: muH/5f6P3sicm/Qo4sty81IDkxsj1eNzUvXZvsk+g8UT9Ce2cGZYlNoGfNgJq87ilHU+kw9mW2hoVoti8svY24BRhC9JC5inBbgsl/jib/5qS2V/PdvKhhjSGIv+3SE6YGsdFtIgjeyfpaqqgcyBUa061yUCA5RS06INIYxWo2zCr/HkSNkAJNMBPu+/yr4hPoUFEQxArs3NkOCo4oQ4g0wM/T83zNaaqQDdPql98Vm2Uo/OH2/bd112RliNQ6a1LesrYgrl5POoXoLGW66LApYWYLkgAUWVRBWmJh8hR/ovwIjsX8gmQUKCuFiseTxY1gA6ms/7w+4rub62RvBQ9Yt5i4RFSiIwEBw+vqwUArTQB8ZuYWC2tfhWaNZFGxwZdDxsFeZbQl9TvJi2zJ9f8c6sjI6sk51RaFAuk6LSUEKx4AhvdE4B7T3OL6KlXIapPiU35bvBnyymylWCUR6QJ1eUREoutEMDm6YyTTFFHOKcxD94hV5DakPX0/57p3iL3V1mIhjjpC+X1zxTrv9Ne/7gqL+RGxEgFLYcf1mxAk61fqHvrb2qhIDW9gPKJi9vVC74haTjV6PQt/KNKy/QdmYh++vAqYAYCNhqa7FQwd+/EQu00tLQHJgyjuOzmr0zE+XZkAgTBEzehfeFwpXmKPQ4GlGH7JullrbRgd+UTBs=

script:
  - "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
notifications:
  slack:
    secure: v8LmDCldbvyoMvKgtvhVykHhUJXcVEBRU1uIoN2QLQ3cviY9Qdtv5+MEuXmDLlmqoiykr9AEGXU6V7KH5CSZhJt1eI8F7lJBfKC/RsMcMvnoIBlawVQMjVTsjw80FOs8wt+oOd00YKJd3LicikQqxsOP+++0vpNACwcNvqXTbGVyjgcVAmD3ptHTNZT0oVaMOOVW6Xfen+YY17cSO/IEuqDrMGMb9ToWeb8dr8mTPu64FwNz9E/hOzkBcF0/AU5lpicECJOaEmofRVMsNmZaPzLYG+4fO5LBHIg3O8gt2lN0/OARenffPrFPFPyhAUzFCLPUkIJw4WNWQbE6nZyvH9llgFfW0RlWqfrw7cszTLYfCX75f7XxlCLkuDTL/2x9Pu3efRYOdNXUhaQIZ22uWWIwO8lpP1ufZCBvgUxsxN8JHCk60ZMXlOtN+NeNcSXH++Uqdc9FJlsc3mkiBHKNjPGlKbaDRgte/SvU5+Ze/O8nSdJDGzRcM99otRAwiBktthMzjKwTsugMRH/8nNz7CVoKOTsQQBBTaf2MhJfxzSvCvsUruRtbXGOrmHzmm8Bh4cr5OXRVY6ETSooB2oZEysArIlw7rmyAez3CGnu2gr2lz3EyZp9UHuWsBbbAcZBBcBmpG2MHOlx45bDMaADiBRZpCMsGdvlvMaESwcM+9SI=
