language: java
jdk:
  - openjdk11
script:
  - "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
notifications:
  slack:
    secure: v8LmDCldbvyoMvKgtvhVykHhUJXcVEBRU1uIoN2QLQ3cviY9Qdtv5+MEuXmDLlmqoiykr9AEGXU6V7KH5CSZhJt1eI8F7lJBfKC/RsMcMvnoIBlawVQMjVTsjw80FOs8wt+oOd00YKJd3LicikQqxsOP+++0vpNACwcNvqXTbGVyjgcVAmD3ptHTNZT0oVaMOOVW6Xfen+YY17cSO/IEuqDrMGMb9ToWeb8dr8mTPu64FwNz9E/hOzkBcF0/AU5lpicECJOaEmofRVMsNmZaPzLYG+4fO5LBHIg3O8gt2lN0/OARenffPrFPFPyhAUzFCLPUkIJw4WNWQbE6nZyvH9llgFfW0RlWqfrw7cszTLYfCX75f7XxlCLkuDTL/2x9Pu3efRYOdNXUhaQIZ22uWWIwO8lpP1ufZCBvgUxsxN8JHCk60ZMXlOtN+NeNcSXH++Uqdc9FJlsc3mkiBHKNjPGlKbaDRgte/SvU5+Ze/O8nSdJDGzRcM99otRAwiBktthMzjKwTsugMRH/8nNz7CVoKOTsQQBBTaf2MhJfxzSvCvsUruRtbXGOrmHzmm8Bh4cr5OXRVY6ETSooB2oZEysArIlw7rmyAez3CGnu2gr2lz3EyZp9UHuWsBbbAcZBBcBmpG2MHOlx45bDMaADiBRZpCMsGdvlvMaESwcM+9SI=
