language: java
jdk:
  - openjdk11
addons:
  sonarcloud:
    organization: "sulekhadahiya-github"
    token:
      secure: QrmSGVJm1DhoGrNytf8Bv6g84eUwXQnlUBg+63LNou99AxQXtn/aouIiMdYJ0HLNb7fjCUkwH3TETc7a34nVl+lcVgmvSWeg7VY1eweCjscpppkMBX5kvq4xcCyOw9pWcUblGXD0EZPwM9xx7ji3n+lV0fVtulPT7B5WuFxTTPwZtFOcR2KIEvRnAxHqHXlU5B7DBOGl43BnIdNWlmuY25Xc1YtFCWbjBNKVP4Cldco+HxL1PEoe2dtbLDDLzK5F1Qf8lVIicuYsLFFwNcrYb3C4zm+hDBAPCtz9j6uvjsqfpsawZoF/GjJHayXxwdFDtrycd3OI7lhf9ave9d5GwOBjCl72bnUfp8Af5YjwvueGInRgNLJU4DYDU3Pp8d7ufemZnCvXMMSEwnxA8O/o9WBN70nsyzR7oOM/C4E/zUjwfPGnMsH6FgjyYWRmvOVtbc5NiQE1KxkQJr8MslOIp4+cXlMLL6dMWXsON7Y85//kWB1R8JO9WrHKWadvZuRe1KJXkGoqVw3FmSQEyjR6QGS7o8lDbcgGhin+IVC6tYo/ORcmcCkGT3HgBC4OnIYAnTAFDFXtcFNc51f7eQl6P3YUDpmjpL3VF5DRt+m8lkRnA4qiNaYkww2ojhYkRTzNywUQeVKAjkerfc3bB8v3660BX0YWrAhKsS1oknhF0SI=
script:
  - "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
  - "./mvnw org.jacoco:jacoco-maven-plugin:prepare-agent install -DskipTests=true sonar:sonar"
notifications:
  slack:
    secure: v8LmDCldbvyoMvKgtvhVykHhUJXcVEBRU1uIoN2QLQ3cviY9Qdtv5+MEuXmDLlmqoiykr9AEGXU6V7KH5CSZhJt1eI8F7lJBfKC/RsMcMvnoIBlawVQMjVTsjw80FOs8wt+oOd00YKJd3LicikQqxsOP+++0vpNACwcNvqXTbGVyjgcVAmD3ptHTNZT0oVaMOOVW6Xfen+YY17cSO/IEuqDrMGMb9ToWeb8dr8mTPu64FwNz9E/hOzkBcF0/AU5lpicECJOaEmofRVMsNmZaPzLYG+4fO5LBHIg3O8gt2lN0/OARenffPrFPFPyhAUzFCLPUkIJw4WNWQbE6nZyvH9llgFfW0RlWqfrw7cszTLYfCX75f7XxlCLkuDTL/2x9Pu3efRYOdNXUhaQIZ22uWWIwO8lpP1ufZCBvgUxsxN8JHCk60ZMXlOtN+NeNcSXH++Uqdc9FJlsc3mkiBHKNjPGlKbaDRgte/SvU5+Ze/O8nSdJDGzRcM99otRAwiBktthMzjKwTsugMRH/8nNz7CVoKOTsQQBBTaf2MhJfxzSvCvsUruRtbXGOrmHzmm8Bh4cr5OXRVY6ETSooB2oZEysArIlw7rmyAez3CGnu2gr2lz3EyZp9UHuWsBbbAcZBBcBmpG2MHOlx45bDMaADiBRZpCMsGdvlvMaESwcM+9SI=

